help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

setup: clean  ## Setup development environment
	uv venv --clear --system-site-packages
	uv sync --all-extras
	uv run pre-commit install


format: ## Run pre-commit hooks
	uv run pre-commit run -a

test: ## Run all tests (excludes e2e; see test-e2e)
	uv run pytest -v -m "not e2e"

test-no-hardware: ## Run tests without hardware
	uv run pytest -v -m "not hardware and not e2e"

test-e2e: ## Run WebUI full-stack E2E (live uvicorn + HTTP/WS/MJPEG)
	uv run pytest -v -m e2e

type: ## Run type check
	uv run pyright

webui-dev: ## Run WebUI dev server (auto-reload)
	uv run uvicorn webui.app:create_app --factory --reload --host 0.0.0.0 --port 8080

webui: ## Run WebUI server
	uv run python -m webui

webui-fake: ## Run WebUI with fake camera (isolated data_dir/port; for manual/browser E2E)
	PCBASM_WEBUI_FAKE_CAMERA=1 \
	PCBASM_WEBUI_PORT=$${PCBASM_WEBUI_PORT:-8099} \
	PCBASM_WEBUI_DATA_DIR=$${PCBASM_WEBUI_DATA_DIR:-/tmp/pcbasm-webui-fake} \
	uv run python -m webui

run: format test type ## Run all workflow.
	@echo "All tasks completed successfully."
