help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

setup: clean  ## Setup development environment
	uv venv --clear --system-site-packages
	uv sync --all-extras
	uv run pre-commit install


format: ## Run pre-commit hooks
	uv run pre-commit run -a

test: ## Run all tests (excludes e2e; see test-e2e)
	uv run pytest -v -m "not e2e"

test-no-hardware: ## Run tests without hardware
	uv run pytest -v -m "not hardware and not e2e"

test-e2e: ## Run WebUI full-stack E2E (live uvicorn + HTTP/WS/MJPEG)
	uv run pytest -v -m e2e --timeout=180

playwright-install: ## Install Playwright-managed Chromium when system chromium is unavailable
	uv run playwright install chromium

migrate-codex: ## Generate Codex rules from Claude settings
	uv run python scripts/migrate_codex.py

migrate-codex-check: ## Check whether generated Codex rules are current
	uv run python scripts/migrate_codex.py --check

type: ## Run type check
	uv run pyright

api-dev: ## Run backend WebAPI dev server (auto-reload)
	uv run uvicorn web.api.app:create_app --factory --reload --host 0.0.0.0 --port 8081

api: ## Run backend WebAPI server
	uv run python -m web.api

api-fake: ## Run backend WebAPI with fake camera (isolated data_dir/port; for manual/browser E2E)
	PCBASM_API_FAKE_CAMERA=1 \
	PCBASM_API_PORT=$${PCBASM_API_PORT:-8099} \
	PCBASM_API_DATA_DIR=$${PCBASM_API_DATA_DIR:-/tmp/pcbasm-webui-fake} \
	uv run python -m web.api

ui-dev: ## Run UI frontend dev server (auto-reload)
	uv run uvicorn web.ui.app:create_app --factory --reload --host 0.0.0.0 --port 8080

ui: ## Run UI frontend server
	uv run python -m web.ui

# 隔離ポートの frontend を api-fake（8099）へ向ける。machines は env で渡せない
# （マシン一覧は machines_file と mDNS 探索が真実）ので静的登録を 1 台だけ生成する
ui-fake: ## Run UI frontend against api-fake (isolated port; for manual/browser E2E)
	@mkdir -p $${PCBASM_UI_FAKE_DIR:-/tmp/pcbasm-ui-fake}
	@printf '[[machine]]\nmachine_id = "fake"\nhost = "127.0.0.1"\nport = %s\nname = "fake backend"\n' \
		"$${PCBASM_API_PORT:-8099}" > $${PCBASM_UI_FAKE_DIR:-/tmp/pcbasm-ui-fake}/machines.toml
	PCBASM_UI_PORT=$${PCBASM_UI_PORT:-8098} \
	PCBASM_UI_MACHINES_FILE=$${PCBASM_UI_FAKE_DIR:-/tmp/pcbasm-ui-fake}/machines.toml \
	uv run python -m web.ui

# 旧名のエイリアス。実機の pcbasm-webui.service が ExecStart=make webui を参照している
# ため、systemd unit を api / ui の 2 本に分けるまで残す
webui-dev: api-dev ## Alias for api-dev (deprecated)

webui: api ## Alias for api (referenced by pcbasm-webui.service)

webui-fake: api-fake ## Alias for api-fake (deprecated)

run: format test type ## Run all workflow.
	@echo "All tasks completed successfully."
