help:  ## Show help
	@grep -E '^[.0-9a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

setup: clean  ## Setup development environment
	uv venv --clear --system-site-packages
	uv sync --all-extras
	uv run pre-commit install

# ML 依存は WebAPI / UI の実行環境へ無条件に入れない（AGENTS.md「プロジェクト概要」）。
# GPU 学習ワークステーション向けに学習・探索・export を明示的に足す。ml-hpo は
# ml-train を、ml-train は ml-runtime を include するので、この 2 group で足りる。
# uv sync は指定しなかった group を取り除くため、必要な group は 1 コマンドへ並べる。
setup-ml: ## Install ML dependency groups for the GPU training workstation
	uv sync --group ml-hpo --group ml-export
	uv run python scripts/ml_smoke.py

# 推論だけを行う Raspberry Pi 5 用。学習・探索・export の依存は入れない。
setup-ml-runtime: ## Install inference-only ML dependencies (Raspberry Pi 5)
	uv sync --group ml-runtime

ml-smoke: ## Verify the ML development environment (versions, CUDA, forward/backward, decode)
	uv run python scripts/ml_smoke.py


format: ## Run pre-commit hooks
	uv run pre-commit run -a

test: ## Run all tests (excludes e2e; see test-e2e)
	uv run pytest -v -m "not e2e"

test-no-hardware: ## Run tests without hardware
	uv run pytest -v -m "not hardware and not e2e"

# tests/ml はドメイン非依存なので、picamera2 / pcbnew が無い学習機でも通る。
# 装置側のテストを collect しないよう対象を tests/ml へ絞る。
test-ml: ## Run the domain-independent ML tests (works without picamera2/pcbnew)
	uv run pytest -v tests/ml -m "not hardware and not e2e"

test-e2e: ## Run WebUI full-stack E2E (live uvicorn + HTTP/WS/MJPEG)
	uv run pytest -v -m e2e --timeout=180

playwright-install: ## Install Playwright-managed Chromium when system chromium is unavailable
	uv run playwright install chromium

migrate-codex: ## Generate Codex rules from Claude settings
	uv run python scripts/migrate_codex.py

migrate-codex-check: ## Check whether generated Codex rules are current
	uv run python scripts/migrate_codex.py --check

type: ## Run type check
	uv run pyright

api-dev: ## Run backend WebAPI dev server (auto-reload)
	uv run uvicorn web.api.app:create_app --factory --reload --host 0.0.0.0 --port 8081

api: ## Run backend WebAPI server
	uv run python -m web.api

# mDNS を切るのは隔離のため。fake backend は camera と data_dir だけが fake で
# config_dir は実機のものなので、広告すると実機と同じ machine_id が LAN に出る
# （frontend は先に発見した方を残すため、ドロップダウンの実機エントリがこの
# fake backend を指しうる）
api-fake: ## Run backend WebAPI with fake camera (isolated data_dir/port; for manual/browser E2E)
	PCBASM_API_FAKE_CAMERA=1 \
	PCBASM_API_PORT=$${PCBASM_API_PORT:-8099} \
	PCBASM_API_DATA_DIR=$${PCBASM_API_DATA_DIR:-/tmp/pcbasm-webui-fake} \
	PCBASM_API_DISCOVERY_ENABLED=0 \
	uv run python -m web.api

ui-dev: ## Run UI frontend dev server (auto-reload)
	uv run uvicorn web.ui.app:create_app --factory --reload --host 0.0.0.0 --port 8080

ui: ## Run UI frontend server
	uv run python -m web.ui

# 隔離ポートの frontend を api-fake（8099）へ向ける。machines は env で渡せない
# （マシン一覧は machines_file と mDNS 探索が真実）ので静的登録を 1 台だけ生成する。
# mDNS 探索も切る（実 LAN の機体が混ざると「fake backend だけを見る」隔離が壊れる）
ui-fake: ## Run UI frontend against api-fake (isolated port; for manual/browser E2E)
	@mkdir -p $${PCBASM_UI_FAKE_DIR:-/tmp/pcbasm-ui-fake}
	@printf '[[machine]]\nmachine_id = "fake"\nhost = "127.0.0.1"\nport = %s\nname = "fake backend"\n' \
		"$${PCBASM_API_PORT:-8099}" > $${PCBASM_UI_FAKE_DIR:-/tmp/pcbasm-ui-fake}/machines.toml
	PCBASM_UI_PORT=$${PCBASM_UI_PORT:-8098} \
	PCBASM_UI_MACHINES_FILE=$${PCBASM_UI_FAKE_DIR:-/tmp/pcbasm-ui-fake}/machines.toml \
	PCBASM_UI_DISCOVERY_ENABLED=0 \
	uv run python -m web.ui

run: format test type ## Run all workflow.
	@echo "All tasks completed successfully."
