[klipper]
host = "localhost"
port = 7125

[probe]
a_pin = 17
b_pin = 27
rotation_pulse = 600      # PPR (Pulses Per Rotation)
rotation_distance = 40.0  # mm/回転
inverse = true

[paste_dispenser]
syringe_size = 9.0 # シリンジの直径 [mm]
nozzle_size = "G27" # ノズルのゲージ

[camera]
device_id = 0
width = 640
height = 480
fps = 30.0
format = "YUYV"
calibration_file = "HD USB Camera: HD USB Camera_20260106_160859.json"

[camera.crop]
width = 400
height = 400

[toolhead]
# カメラに対するツールヘッドの相対位置 (mm)
x = 13.2
y = 54.7

[reference_point]
# 基準点（top left）のおおよその絶対位置 (mm)
x = 23.4
y = 7.9
# 基準点の直径 (mm)
target_diameter = 3.0

# 基盤からみた基準点の相対位置 (mm)
[reference_point.offsets] # [x, y]で記述
top_left = [0.0, -5.0]
top_right = [0.0, -5.0]
bottom_left = [5.0, 5.0]
# bottom_right = [-5.0, 5.0]
