[klipper]
host = "localhost"
port = 7125

[paste_dispenser]
rotations_per_ul = 1.0 # 1μLあたりの回転数 [rev/μL]
nozzle_size = "23G" # ノズルのゲージ
dispense_rate = 3.0 # 吐出レート [uL/sec]
dispense_accel = 10.0 # 吐出加速度 [uL/sec^2]
retract_amount = 1 # リトラクション量 [uL]
retract_rate = 5.0 # リトラクションレート [uL/sec]
retract_accel_factor = 2.0 # リトラクション加速度係数
paste_height = 0.0 # 塗布面のZ高さ [mm]
ul_per_mm2 = 5.0 # パッド面積あたりのペースト量 [uL/mm^2]
prime_extra_delay = 0.4 # プライム後の追加遅延 [sec]

[paste_dispenser.toolhead]
# カメラに対するツールヘッドの相対位置 (mm)

# 設計値
# x = 0
# y = 26.46

# 実測値
x = -1.4829347970566218
y = 23.36368618204949

[camera]
device_id = 0
width = 1280
height = 720
fps = 30.0
format = "YUYV"
calibration_file = "ov9281_20260402_163428.json"

[camera.crop]
width = 600
height = 600

[probe]
servo_name = "probe_gnd"
# rack and pinion: π × module × teeth = π × 0.8 × 16 ≈ 40.212
revolution_distance = 40.212 # サーボ一回転あたりの移動量 [mm]
down_distance = 3.8          # グラウンドを下げる距離 [mm]
min_radius = 0.5             # サンプル点が銅箔境界から確保すべき最小距離 [mm]

[reference_point]
# 基準点（top left）のおおよその絶対位置 (mm)
x = 18
y = 5
# 基準点の直径 (mm)
target_diameter = 3.0

# 基盤からみた基準点の相対位置 (mm)
[reference_point.offsets] # [x, y]で記述
top_left = [5.0, -5.0]
top_right = [-5.0, -5.0]
bottom_left = [5.0, 5.0]
# bottom_right = [-5.0, 5.0]
